inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/Encoding:
  Enabled: false
