inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/Encoding:
  Enabled: false
