#!/bin/bash -e

command_name=$1
command_args=${@:2}

# we are relying on docker, adding a descriptive name here
# will help when identifiying containers with docker ps
image_name="heartcheck"

# helper to bring container alive
run() {
  args=${@:1}
  docker-compose run --rm -v $PWD:/heartcheck app $args
}

case $command_name in
  setup)
    docker-compose build
    run bundle install
    ;;
  bash)
    run bash
    ;;
  bundle)
    run bundle install
    ;;
  console)
    run bin/console
    ;;
  rspec)
    run bundle exec rspec
    ;;
  usage)
    echo -e "Usage:\n"
    echo -e "heartcheck bash       - access docker sh console"
    echo -e "heartcheck bundle     - runs bundle install"
    echo -e "heartcheck console    - runs a irb console"
    echo -e "heartcheck rspec      - runs rspec"
    echo -e "heartcheck setup      - setups docker image"
    ;;
  *)
    $0 usage
  ;;
esac

